---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-workload-protection
    kind: solution
    catalog_id: _
    offering_id: _
    variations:
      - name: standard
        mark_ready: true
        install_type: extension
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
